/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.oac;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cris-
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public boolean Teste = false;
    public boolean Configuracoes = false;

    private final TrabalhoOAC principal = new TrabalhoOAC();

    public Frame() {
        initComponents();
        Direto.setEnabled(false);
        AAleatorio.setEnabled(false);
        AFIFO.setEnabled(false);
        AFrequente.setEnabled(false);
        ARecente.setEnabled(false);
        ACAleatorio.setEnabled(false);
        ACFIFO.setEnabled(false);
        ACFrequente.setEnabled(false);
        ACRecente.setEnabled(false);

        setTitle("Simulador Memória Cache");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    public void Verifica() {
        if (Teste && Configuracoes) {

            Direto.setEnabled(true);
            AAleatorio.setEnabled(true);
            AFIFO.setEnabled(true);
            AFrequente.setEnabled(true);
            ARecente.setEnabled(true);
            ACAleatorio.setEnabled(true);
            ACFIFO.setEnabled(true);
            ACFrequente.setEnabled(true);
            ACRecente.setEnabled(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Config = new javax.swing.JButton();
        Test = new javax.swing.JButton();
        Direto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AAleatorio = new javax.swing.JButton();
        AFIFO = new javax.swing.JButton();
        AFrequente = new javax.swing.JButton();
        ARecente = new javax.swing.JButton();
        ACAleatorio = new javax.swing.JButton();
        ACFIFO = new javax.swing.JButton();
        ACFrequente = new javax.swing.JButton();
        ACRecente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Config.setText("Configurações");
        Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigActionPerformed(evt);
            }
        });

        Test.setText("Teste");
        Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestActionPerformed(evt);
            }
        });

        Direto.setText("Direto");
        Direto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiretoActionPerformed(evt);
            }
        });

        jLabel1.setText("MAPEAMENTO");

        jLabel2.setText("Entrada de Arquivos");

        AAleatorio.setText("Aleatorio");
        AAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AAleatorioActionPerformed(evt);
            }
        });

        AFIFO.setText("FIFO");
        AFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFIFOActionPerformed(evt);
            }
        });

        AFrequente.setText("Frequente");
        AFrequente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFrequenteActionPerformed(evt);
            }
        });

        ARecente.setText("Recente");
        ARecente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARecenteActionPerformed(evt);
            }
        });

        ACAleatorio.setText("Aleatorio");
        ACAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACAleatorioActionPerformed(evt);
            }
        });

        ACFIFO.setText("FIFO");
        ACFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACFIFOActionPerformed(evt);
            }
        });

        ACFrequente.setText("Frequente");
        ACFrequente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACFrequenteActionPerformed(evt);
            }
        });

        ACRecente.setText("Recente");
        ACRecente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACRecenteActionPerformed(evt);
            }
        });

        jLabel3.setText("Associativo");

        jLabel4.setText("Associativo em Conjunto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Config)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Test)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Direto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AFIFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AFrequente, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(ARecente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ACAleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACFIFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACFrequente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACRecente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direto)
                    .addComponent(ACAleatorio)
                    .addComponent(AAleatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACFIFO)
                    .addComponent(AFIFO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACFrequente)
                    .addComponent(AFrequente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACRecente)
                    .addComponent(ARecente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Config)
                    .addComponent(Test))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigActionPerformed
        try {
            // TODO add your handling code here:

            principal.LeituraDasConfiguracos();
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Configuracoes = true;
        Verifica();
    }//GEN-LAST:event_ConfigActionPerformed

    private void DiretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiretoActionPerformed
        // TODO add your handling code here:

        Direto direto = new Direto();
        principal.MapeamentoDiretoBinary(direto);

        direto.setVisible(true);


    }//GEN-LAST:event_DiretoActionPerformed

    private void TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestActionPerformed
        try {
            // TODO add your handling code here:
            principal.LeituraDosTeste();
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Teste = true;
        Verifica();
    }//GEN-LAST:event_TestActionPerformed

    private void AAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AAleatorioActionPerformed
        // TODO add your handling code here:

        Associativo associativo = new Associativo();
        associativo.setVisible(true);
        principal.AleatorioAssociativoBinary(associativo);

    }//GEN-LAST:event_AAleatorioActionPerformed

    private void AFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFIFOActionPerformed
        // TODO add your handling code here:

        Associativo associativo = new Associativo();
        associativo.setVisible(true);
        principal.FIFOAssociativoBinary(associativo);


    }//GEN-LAST:event_AFIFOActionPerformed

    private void AFrequenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFrequenteActionPerformed
        // TODO add your handling code here:

        Associativo associativo = new Associativo();
        associativo.setVisible(true);
        principal.FrequenteAssociativoBinary(associativo);


    }//GEN-LAST:event_AFrequenteActionPerformed

    private void ARecenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARecenteActionPerformed

        // TODO add your handling code here:
        Associativo associativo = new Associativo();
        associativo.setVisible(false);
        principal.RecenteAssociativoBinary(associativo);
    }//GEN-LAST:event_ARecenteActionPerformed

    private void ACAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACAleatorioActionPerformed

        AConjunto conjunto = new AConjunto();
        conjunto.setVisible(false);
        AssociativoConjunto ac = new AssociativoConjunto(principal, conjunto, 0);
        ac.setVisible(true);


    }//GEN-LAST:event_ACAleatorioActionPerformed

    private void ACFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACFIFOActionPerformed
        // TODO add your handling code here:
        AConjunto conjunto = new AConjunto();
        conjunto.setVisible(false);
        AssociativoConjunto ac = new AssociativoConjunto(principal, conjunto, 1);
        ac.setVisible(true);
    }//GEN-LAST:event_ACFIFOActionPerformed

    private void ACFrequenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACFrequenteActionPerformed
        // TODO add your handling code here:
        AConjunto conjunto = new AConjunto();
        conjunto.setVisible(false);
        AssociativoConjunto ac = new AssociativoConjunto(principal, conjunto, 2);
        ac.setVisible(true);
    }//GEN-LAST:event_ACFrequenteActionPerformed

    private void ACRecenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACRecenteActionPerformed
        // TODO add your handling code here:
        AConjunto conjunto = new AConjunto();
        conjunto.setVisible(false);
        AssociativoConjunto ac = new AssociativoConjunto(principal, conjunto, 3);
        ac.setVisible(true);

    }//GEN-LAST:event_ACRecenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AAleatorio;
    private javax.swing.JButton ACAleatorio;
    private javax.swing.JButton ACFIFO;
    private javax.swing.JButton ACFrequente;
    private javax.swing.JButton ACRecente;
    private javax.swing.JButton AFIFO;
    private javax.swing.JButton AFrequente;
    private javax.swing.JButton ARecente;
    private javax.swing.JButton Config;
    private javax.swing.JButton Direto;
    private javax.swing.JButton Test;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
